#!/bin/bash

# Generate a private key for the CA
openssl genpkey -algorithm RSA -out ./certs/ca.key -aes256

# Generate a self-signed CA certificate
openssl req -x509 -new -nodes -key ./certs/ca.key -sha256 -days 365 -out ./certs/ca.crt

# Generate a private key for the signing certificate
openssl genpkey -algorithm RSA -out ./certs/agent.key -aes256

# Generate a Certificate Signing Request (CSR)
openssl req -new -key ./certs/agent.key -out ./certs/agent.csr

# Sign the CSR with the CA certificate
openssl x509 -req -in ./certs/agent.csr -CA ca.crt -CAkey ./certs/ca.key -CAcreateserial -out ./certs/agent.crt -days 365 -sha256

